baseURL = "https://zarine.net"
title = "Zarine Kharazian"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Your site description"
  copyright = "copyright © 2023 zarine kharazian"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "publications"
    title = "publications"
    url = "/publications/"
    weight = 20
    
  [[menu.main]]
    identifier = "cv"
    name = "cv"
    title = "cv"
    url = "/cv.pdf/"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true