baseURL: "https://zarinekharazian.github.io/"
title: zarine kharazian
theme: etch
languageCode: en-US
enableInlineShortcodes: yes
pygmentsCodeFences: yes
pygmentsUseClasses: yes
params:
  copyright: Copyright © 2022 zarine kharazian
  dark: on 
  description: Your site description
  highlight: true
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /posts
      weight: 10
    - identifier: cv
      name: cv
      title: cv
      url: /cv.pdf
      weight: 20
#permalinks:
#  posts: /:title/
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    ordered: yes
