baseURL: "https://zarine.net"
title: zarine kharazian
theme: etch
languageCode: en-US
enableInlineShortcodes: yes
pygmentsCodeFences: yes
pygmentsUseClasses: yes
params:
  copyright: copyright © 2022 zarine kharazian
  dark: on 
  highlight: true
menu:
  main:
    - identifier: posts
      name: posts
      title: posts
      url: /posts
      weight: 10
    - identifier: cv
      name: cv
      title: cv
      url: /cv.pdf
      weight: 20
    - identifier: publications
      name: publications
      title: publications
      url: /publications
      weight: 30

permalinks:
  posts: /:title/ 
  
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    ordered: yes
